# If you're me and trying to debug this thing without committing even more
# crimes to the dev branch, you can attempt to use forgejo-runner to run this
# thing locally.
#
# Cache may not work though, and to fix this, unfortunately you'll need to
# comment out any cache references (ex. cache: "pnpm", actions/cache)
on:
  push:
    branches:
      - main
      - dev
    paths:
      - ".forgejo/workflows/build.yaml"
      - "public/**"
      - "src/**"
      - astro.config.ts
      - devbox.json
      - devbox.lock
      - svelte.config.js
      - wrangler.jsonc
  workflow_dispatch:

env:
  CLOUDFLARE_PROJECT_NAME: queerwinnipeg
  DIST_FOLDER: ./dist

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  Build:
    runs-on: docker
    container:
      image: code.forgejo.org/oci/node:22-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      # Version should be specified by the packageManager key in package.json
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          # cache: "pnpm"

      # I don't want to debug this
      # See https://git.gay/queerwinnipeg/queerwinnipeg.ca/actions/runs/4 if
      # you want to sink some hours into it
      #
      # - name: Install devbox for pnpm and Node.js
      #   uses: https://github.com/jetify-com/devbox-install-action@v0.12.0
      #   with:
      #     enable-cache: "true"
      # - name: Cache node_modules from pnpm
      #   id: cache-npm
      #   uses: actions/cache@v4
      #   env:
      #     cache-name: cache-node_modules
      #   with:
      #     path: .pnpm-store
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-
      # - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      #   name: List the state of node_modules
      #   continue-on-error: true
      #   run: pnpm list

      - name: Install dependencies from npm
        run: pnpm install --frozen-lockfile

      # - name: Cache image build output
      #   uses: actions/cache@v4
      #   env:
      #     cache-name: cache-images
      #   with:
      #     path: .astro-cache
      #     key: build-${{ env.cache-name }}
      #     restore-keys: build-${{ env.cache-name }}

      - name: Build
        run: pnpm build

      - uses: actions/upload-artifact@v4
        with:
          name: dist-output
          path: $DIST_FOLDER
          include-hidden-files: true
          compression-level: 0 # Assumes majority of assets are incompressible images

  Deploy:
    runs-on: docker
    needs: Build
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-output

      - name: Deploy
        uses: https://github.com/cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy "$DIST_FOLDER" --commit-dirty false
