on:
  push:
    branches:
      - main
      - dev
    paths:
      - ".forgejo/workflows/build.yaml"
      - "public/**"
      - "src/**"
      - astro.config.ts
      - devbox.json
      - devbox.lock
      - svelte.config.js
      - wrangler.jsonc
  workflow_dispatch:

env:
  CLOUDFLARE_PROJECT_NAME: queerwinnipeg
  DIST_FOLDER: ./dist

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  Build:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: "pnpm"

      - name: Install devbox for pnpm and Node.js
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: "true"

      - name: Cache node_modules from pnpm
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node_modules
        with:
          path: .pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node_modules
        continue-on-error: true
        run: pnpm list

      - name: Install dependencies from npm
        run: |
          pnpm config set store-dir .pnpm-store 
          pnpm install --frozen-lockfile

      - name: Cache image build output
        uses: actions/cache@v4
        env:
          cache-name: cache-images
        with:
          path: .astro-cache
          key: build-${{ env.cache-name }}
          restore-keys: build-${{ env.cache-name }}

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy "$DIST_FOLDER" --commit-dirty false
